# Generated by Django 3.1.4 on 2021-09-28 06:31

from django.db import migrations, models
import leave.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Leave',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_id', models.CharField(default=leave.models.Leave.auto_comp_id, editable=False, max_length=25)),
                ('user', models.CharField(max_length=40)),
                ('email', models.CharField(max_length=50)),
                ('leave_type', models.CharField(choices=[('sick', 'sick'), ('planned', 'planned'), ('unplanned', 'unplanned')], default='planned', max_length=20)),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('reason', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('requested', 'requested'), ('approved', 'approved'), ('declined', 'declined')], default='requested', max_length=20)),
            ],
            options={
                'verbose_name': 'Leave',
                'verbose_name_plural': 'Leaves',
                'ordering': ('-id',),
            },
        ),
    ]
