# Generated by Django 3.1.4 on 2021-09-28 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210826_1452'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='employee_leaves',
            field=models.IntegerField(blank=True, default=20, null=True),
        ),
    ]
