# Generated by Django 3.1.4 on 2021-08-27 09:00

import components.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ComponentCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(upload_to='component_category')),
            ],
        ),
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('component_id', models.CharField(default=components.models.Component.auto_comp_id, max_length=20)),
                ('name', models.CharField(max_length=75, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('component_location', models.CharField(default='inventory', max_length=100)),
                ('vendor', models.CharField(blank=True, max_length=100, null=True)),
                ('date_of_order', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='components')),
                ('avialable', models.BooleanField(default=True)),
                ('stock', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='components.componentcategory')),
            ],
        ),
    ]
