# Generated by Django 3.1.4 on 2021-08-27 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='components'),
        ),
        migrations.AlterField(
            model_name='componentcategory',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='component_category'),
        ),
    ]
