# Generated by Django 3.1.4 on 2021-08-27 09:07

import components.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0002_auto_20210827_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='component_id',
            field=models.CharField(default=components.models.Component.auto_comp_id, max_length=20, unique=True),
        ),
    ]
