# Generated by Django 3.1.4 on 2021-08-27 09:25

import components.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0003_auto_20210827_1437'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='component',
            options={'ordering': ('name', 'category'), 'verbose_name': 'Components'},
        ),
        migrations.AlterModelOptions(
            name='componentcategory',
            options={'ordering': ('name',), 'verbose_name': 'Component Category', 'verbose_name_plural': 'Component Categories'},
        ),
        migrations.AddField(
            model_name='component',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='componentcategory',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='component',
            name='component_id',
            field=models.CharField(default=components.models.Component.auto_comp_id, editable=False, max_length=20, unique=True),
        ),
    ]
