# Generated by Django 3.1.4 on 2021-09-23 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0005_auto_20210923_1739'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='component',
            name='slug',
        ),
    ]
