# Generated by Django 3.1.4 on 2021-09-24 09:44

import components.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0008_component_invoice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='component_id',
            field=models.CharField(default=components.models.Component.auto_comp_id, editable=False, max_length=20),
        ),
    ]
