# Generated by Django 3.1.4 on 2021-10-04 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0009_auto_20210924_1514'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='component',
            options={'ordering': ('id',), 'verbose_name': 'Components'},
        ),
    ]
