# Generated by Django 3.1.4 on 2021-10-04 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0010_auto_20211004_1039'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='component',
            options={'ordering': ('-id',), 'verbose_name': 'Components'},
        ),
    ]
