# Generated by Django 3.1.4 on 2021-10-05 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0011_auto_20211004_1041'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='component_id_by_vendor',
            field=models.CharField(blank=True, max_length=35, null=True),
        ),
    ]
