# Generated by Django 3.1.4 on 2021-09-22 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('requested', 'requested'), ('approve', 'approve'), ('decline', 'decline'), ('deploy', 'deploy'), ('return', 'return')], default='requested', max_length=50),
        ),
    ]
