# Generated by Django 3.1.4 on 2021-09-22 09:12

from django.db import migrations, models
import django.db.models.deletion
import order.models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_auto_20210922_1120'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deployment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deployment_id', models.CharField(default=order.models.Deployment.auto_dep_id, editable=False, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('username', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name': 'Deployment',
                'verbose_name_plural': 'Deployment',
                'ordering': ('-id',),
            },
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ('-created_at',), 'verbose_name': 'Order', 'verbose_name_plural': 'Orders'},
        ),
        migrations.AlterModelOptions(
            name='orderitem',
            options={'ordering': ('-id',), 'verbose_name': 'Order Item', 'verbose_name_plural': 'Order Items'},
        ),
        migrations.CreateModel(
            name='DeployedItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('component', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
                ('deployment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.deployment')),
            ],
            options={
                'verbose_name': 'Deployed Item',
                'verbose_name_plural': 'Deployed Items',
                'ordering': ('-id',),
            },
        ),
    ]
