# Generated by Django 3.1.4 on 2021-09-22 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_auto_20210922_1442'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='deployed_by',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='deployed_into',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='deployment',
            name='email',
            field=models.CharField(editable=False, max_length=30),
        ),
        migrations.AlterField(
            model_name='deployment',
            name='username',
            field=models.CharField(editable=False, max_length=30),
        ),
    ]
