# Generated by Django 3.1.4 on 2021-09-22 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_auto_20210922_1747'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='deployed_by',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='deployed_into',
        ),
        migrations.AddField(
            model_name='deployeditems',
            name='deployed_by',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='deployeditems',
            name='deployed_into',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
