# Generated by Django 3.1.4 on 2021-09-23 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_auto_20210922_1751'),
    ]

    operations = [
        migrations.AddField(
            model_name='deployeditems',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
