# Generated by Django 3.1.4 on 2021-10-06 08:20

from django.db import migrations, models
import order.models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_deployeditems_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.CharField(default=order.models.Order.auto_order_id, editable=False, max_length=25),
        ),
    ]
